version:                    "3"
services:
  federationpostgres:
      image:                postgres
      container_name:       postgres-federation
      restart:              unless-stopped
      volumes:
        - ~/stellar/federation/postgresql:/var/lib/postgresql/data
      env_file: .env
      environment:
        POSTGRES_USER:      ${POSTGRES_USER}
        POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
        POSTGRES_DB:        ${POSTGRES_DB:-federationdb}
      networks:
          - default

  federation:
      build:                ./federation-docker
      container_name:       stellar-federation
      volumes:
        - ~/stellar/federation:/opt/federation
      restart:              unless-stopped
      depends_on:
        - federationpostgres
      env_file: .env
      environment:
        FEDERATION_PORT:    ${FEDERATION_PORT:-8801}
        POSTGRES_USER:      ${POSTGRES_USER}
        POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
        POSTGRES_DB:        ${POSTGRES_DB:-federationdb}
        FEDERATION_DB_TYPE: postgres
        FEDERATION_HOME:    /opt/federation
        FEDERATION_DB_DSN:  "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@federationpostgres/federationdb?sslmode=disable"
      ports:
        - "${FEDERATION_PORT:-8801}:${FEDERATION_PORT:-8801}"
      networks:
          - default
